//
//  calendarPresenter.swift
//  calendar
//
//  Created by iraiAnbu on 30/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol calendarPresentationLogic
{
    func presentSomething(response: CalendarVC.Something.Response)
}

class calendarPresenter: calendarPresentationLogic
{
    weak var viewController: calendarDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CalendarVC.Something.Response)
    {
        var viewModel = CalendarVC.Something.ViewModel()
        viewModel.days = response.days
        viewModel.numberOfWeeksinBaseDate = response.numberOfWeeksinBaseDate
        viewModel.baseDate = response.baseDate
        viewController?.displaySomething(viewModel: viewModel)
    }
}
